# Generated by Django 4.2.4 on 2023-11-20 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/static/img/avatar.jpg', null=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
